Repository 33-1-3/33-1-3, pull requests merged in 2022-12, with the labels that each got.

#5 프로젝트 초기 환경 설정 - ESLint, Prettier, Storybook
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: Config

#4 라우팅 구현 및 기획발표용 각 페이지 목업
  index.html
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/components/index.tsx
  src/hooks/useItem.js
  src/index.css
  src/pages/Home/components/index.tsx
  src/pages/Home/index.tsx
  src/pages/Item/components/index.tsx
  src/pages/Item/index.tsx
  src/pages/MyCollection/components/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/index.tsx
  src/pages/MyCollections/index.tsx
  src/pages/MyItem/components/index.tsx
  src/pages/MyItem/index.tsx
  src/pages/SearchResult/components/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/components/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/components/index.tsx
  src/pages/Signup/index.tsx
  src/utils/getSearchInfo.js
Labels: Implement

#8 기획발표를 위한 로고 이미지 추가
  public/logo.png
  src/App.tsx
  src/pages/Home/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/SearchResult/index.tsx
Labels: Implement

#29 API 훅 오류수정입니다
  src/pages/SearchResult/index.tsx
Labels: Bug

#31 폰트 파일 임시 적용 및 assets 폴더 하위 파일 경로 수정
  index.html
  package-lock.json
  public/LINESeedKR-Bd.woff
  public/LINESeedKR-Rg.woff
  public/LINESeedKR-Th.woff
  public/assets/LINESeedKR-Bd.ttf
  public/assets/LINESeedKR-Rg.ttf
  public/assets/LINESeedKR-Th.ttf
  public/assets/logo.png
  src/App.tsx
  src/common/styles/globalStyle.ts
  src/common/styles/normalizeStyle.ts
  src/pages/Home/index.tsx
  vite.config.ts
Labels: Implement

#33 Bookshelf 컴포넌트 구현
  .prettierignore
  .storybook/preview-head.html
  public/assets/shelf0.svg
  public/assets/shelf1.svg
  public/assets/shelf2.svg
  public/assets/shelf3.svg
  public/assets/shelf4.svg
  public/assets/shelf5.svg
  src/common/styles/normalizeStyle.ts
  src/pages/MyCollections/components/Bookshelf.stories.tsx
  src/pages/MyCollections/components/Bookshelf.tsx
  src/pages/MyCollections/components/index.ts
  src/pages/MyCollections/components/index.tsx
  src/pages/MyCollections/index.tsx
Labels: Implement, React, Config

#36 IconButton 컴포넌트 구현
  .storybook/main.js
  .storybook/preview.js
  .storybook/preview.jsx
  index.html
  package-lock.json
  package.json
  public/assets/LINESeedKR-Bd.woff
  public/assets/LINESeedKR-Rg.woff
  public/assets/LINESeedKR-Th.woff
  src/assets/minus.svg
  src/assets/pencil.svg
  src/assets/plus.svg
  src/common/components/IconButton.stories.tsx
  src/common/components/IconButton.tsx
  src/common/components/index.ts
  src/common/styles/globalStyle.ts
  src/common/styles/normalizeStyle.ts
  src/main.tsx
  src/pages/MyCollections/components/Bookshelf.stories.tsx
  src/pages/MyCollections/components/Bookshelf.tsx
  src/pages/MyCollections/components/index.ts
  src/types/assets.d.ts
  vite.config.ts
Labels: Enhancement, Implement, React, Config

#35 LPCover 컴포넌트 구현
  .storybook/preview-head.html
  package.json
  public/assets/cover.svg
  public/assets/vinyl.svg
  src/App.tsx
  src/common/components/LPCover.stories.tsx
  src/common/components/LPCover.tsx
  src/common/styles/globalStyle.ts
Labels: Bug, Implement, React, Style, Config

#40 ArrowLink 컴포넌트 구현
  .storybook/preview.jsx
  package.json
  src/assets/arrow.svg
  src/common/components/IconButton.stories.tsx
  src/common/components/IconButton.tsx
  src/pages/Item/components/ArrowLink.stories.tsx
  src/pages/Item/components/ArrowLink.tsx
  src/pages/Item/components/index.ts
  src/pages/Item/components/index.tsx
  src/pages/Item/index.tsx
Labels: Enhancement, Implement, React

#41 컴포넌트 수정 사항 반영 & Story Book 애드온 추가
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.jsx
  package-lock.json
  package.json
  src/common/components/SearchInput/SearchInput.stories.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SquareButton/SquareButton.stories.tsx
  src/common/components/SquareButton/SquareButton.tsx
Labels: Bug, Enhancement, React, Config

#44 Story Book Addon 설치 & 환경 설정
  .storybook/preview.jsx
  src/Test.tsx
  src/common/components/SearchInput/SearchInput.stories.tsx
  src/common/components/SquareButton/SquareButton.stories.tsx
Labels: Config

#45 로그인 & 회원가입 링크 컴포넌트 구현
  package-lock.json
  src/common/components/MoveFormLink/MoveFormLink.stories.tsx
  src/common/components/MoveFormLink/MoveFormLink.tsx
Labels: Implement, React, Style, Config

#46 Logo 컴포넌트 구현 및 타입 에러 수정, 폴더 구조 수정
  public/assets/logo.png
  public/assets/logo.svg
  src/App.tsx
  src/common/components/IconButton/IconButton.stories.tsx
  src/common/components/IconButton/IconButton.tsx
  src/common/components/LPCover.tsx
  src/common/components/LogoLink/LogoLink.stories.tsx
  src/common/components/LogoLink/LogoLink.tsx
  src/common/components/index.ts
  src/pages/Home/components/index.ts
  src/pages/Home/components/index.tsx
  src/pages/Home/index.tsx
  src/pages/Item/components/ArrowLink/ArrowLink.stories.tsx
  src/pages/Item/components/ArrowLink/ArrowLink.tsx
  src/pages/Item/components/index.ts
  src/pages/MyCollection/components/TextInput/TextInput.stories.tsx
  src/pages/MyCollection/components/TextInput/TextInput.tsx
  src/pages/MyCollection/components/index.ts
  src/pages/MyCollection/components/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.stories.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/components/index.ts
  src/pages/MyItem/components/index.ts
  src/pages/MyItem/components/index.tsx
  src/pages/MyItem/index.tsx
  src/pages/SearchResult/components/index.ts
  src/pages/SearchResult/components/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/components/index.ts
  src/pages/Signin/components/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/components/index.ts
  src/pages/Signup/components/index.tsx
  src/pages/Signup/index.tsx
Labels: Bug, Enhancement, Implement, React

#47 검색 결과 개수 컴포넌트 구현
  src/common/components/SearchResultText/SearchResultText.stories.tsx
  src/common/components/SearchResultText/SearchResultText.tsx
Labels: Implement, React, Style

#49 컴포넌트 수정 사항 반영 & Router Addon 추가
  .storybook/main.js
  .storybook/preview.jsx
  package-lock.json
  package.json
  src/common/components/MoveFormLink/MoveFormLink.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SearchResultText/SearchResultText.stories.tsx
  src/common/components/SearchResultText/SearchResultText.tsx
  src/common/components/SquareButton/SquareButton.stories.tsx
  src/common/components/SquareButton/SquareButton.tsx
Labels: Implement, React, Style, Config

#50 CollectionCheckbox 컴포넌트 구현
  public/assets/checkedbox.svg
  public/assets/uncheckedbox.svg
  src/common/components/index.ts
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.stories.tsx
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.tsx
  src/pages/Item/components/index.ts
Labels: Implement, React

#53 앨범 제목 & 가수 이름 컴포넌트 구현
  src/common/components/IconButton/IconButton.stories.tsx
  src/common/components/LPCover/LPCover.stories.tsx
  src/common/components/Link/Link.stories.tsx
  src/common/components/LogoLink/LogoLink.stories.tsx
  src/common/components/ProfileLink/ProfileLink.stories.tsx
  src/common/components/TitleInfo/TitleInfo.stories.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/common/components/index.ts
  src/pages/Item/components/ArrowLink/ArrowLink.stories.tsx
  src/pages/MyCollection/components/TextInput/TextInput.stories.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.stories.tsx
Labels: Implement, React, Style

#55 로그인, 로그아웃 input 컴포넌트 & 로그인, 로그아웃 form 컴포넌트 구현
  package-lock.json
  package.json
  public/assets/id.svg
  public/assets/nickname.svg
  public/assets/pwd.svg
  public/assets/pwdCheck.svg
  src/common/components/SignInAndUpForm/SignInAndUpForm.stories.tsx
  src/common/components/SignInAndUpForm/SignInAndUpForm.tsx
  src/common/components/SignInAndUpInput/SignInAndUpInput.stories.tsx
  src/common/components/SignInAndUpInput/SignInAndUpInput.tsx
  src/common/styles/globalStyle.ts
Labels: Implement, React, Style, Config

#56 AddCollectionButton 컴포넌트 구현
  src/assets/plus-circle.svg
  src/common/components/AddCollectionButton/AddCollectionButton.stories.tsx
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/styles/globalStyle.ts
Labels: Implement, React

#64 LPCover, TextInput, SignInAndUpInput, SignInAndUpForm 컴포넌트 리팩토링 및 버그 수정
  .nvmrc
  package-lock.json
  src/common/components/LPCover/LPCover.stories.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/SignInAndUpForm/SignInAndUpForm.tsx
  src/common/components/SignInAndUpInput/SignInAndUpInput.tsx
  src/pages/MyCollection/components/TextInput/TextInput.tsx
  src/pages/MyCollection/index.tsx
Labels: Bug, Enhancement, React, Config

#62 키-값 형태의 상세 정보 컴포넌트 구현
  .eslintrc.js
  src/common/components/DetailInfo/DetailInfo.stories.tsx
  src/common/components/DetailInfo/DetailInfo.tsx
Labels: Bug, Implement, React, Style

#66 Link 컴포넌트 / Dropdown 컴포넌트 리팩토링
  public/assets/arrow.svg
  src/common/components/Dropdown/ComboInput.tsx
  src/common/components/Dropdown/Dropdown.stories.tsx
  src/common/components/Dropdown/Dropdown.tsx
  src/common/components/Dropdown/ListBox.tsx
  src/common/components/Dropdown/Option.tsx
  src/common/components/SquareLink/SquareLink.stories.tsx
  src/common/components/SquareLink/SquareLink.tsx
Labels: Bug, Enhancement, React

#67 SelectCollectionForm 컴포넌트와 ToggleInputButton 컴포넌트 구현
  package-lock.json
  src/common/components/TextInput/TextInput.stories.tsx
  src/common/components/TextInput/TextInput.tsx
  src/common/components/index.ts
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.stories.tsx
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.tsx
  src/pages/Item/components/SelectCollectionForm/SelectCollectionForm.stories.tsx
  src/pages/Item/components/SelectCollectionForm/SelectCollectionForm.tsx
  src/pages/Item/components/SelectCollectionForm/ToggleInputButton.tsx
  src/pages/Item/components/index.ts
  src/pages/MyCollection/components/index.ts
Labels: Enhancement, Implement, React

#72 로그인폼 버튼 활성화 버그 해결 및 모달 컴포넌트 구현
  src/common/components/Dialog/Dialog.stories.tsx
  src/common/components/Dialog/Dialog.tsx
  src/common/components/SignInAndUpForm/SignInAndUpForm.tsx
Labels: Bug, Implement, React, Style

#70 상세 정보 + 버튼 컴포넌트 구현
  src/common/components/AlbumInfo/AlbumInfo.stories.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/DetailInfo/DetailInfo.stories.tsx
  src/common/components/DetailInfo/DetailInfo.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/utils/mockInfo.ts
Labels: Bug, Enhancement, Implement, React, Style

#75 Header 컴포넌트, Footer에 필요한 컴포넌트 생성 및 수정
  public/assets/discogs.svg
  public/assets/github.svg
  src/common/components/Dropdown/Dropdown.stories.tsx
  src/common/components/Dropdown/Dropdown.tsx
  src/common/components/Header/Header.stories.tsx
  src/common/components/Header/Header.tsx
  src/common/components/ImageLink/ImageLink.stories.tsx
  src/common/components/ImageLink/ImageLink.tsx
  src/common/components/MoveFormLink/MoveFormLink.tsx
  src/common/components/MoveLink/MoveLink.stories.tsx
  src/common/components/MoveLink/MoveLink.tsx
  src/common/components/SquareLink/SquareLink.stories.tsx
  src/common/components/SquareLink/SquareLink.tsx
  src/common/components/index.ts
Labels: Bug, Enhancement, Implement, React, Style

#76 테스트 코드 리팩토링 & 검색 결과 아이템 컴포넌트 구현
  src/common/components/AlbumInfo/AlbumInfo.stories.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/common/components/VinylItem/VinylItem.stories.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/index.ts
  src/utils/mockInfo.ts
Labels: Bug, Enhancement, Implement, React, Style

#81 Footer 컴포넌트 구현 및 외부링크 이동 컴포넌트 수정
  public/assets/discogs.svg
  public/assets/github.svg
  src/common/components/Footer/Footer.stories.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/Header/Header.tsx
  src/common/components/ImageLink/ImageLink.tsx
  src/common/components/index.ts
Labels: Bug, Enhancement, Implement, React, Style

#82 검색 결과 아이템 목록 컴포넌트 구현
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.stories.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/utils/mockInfo.ts
Labels: Enhancement, Implement, React, Style

#85 main 페이지 구현(View), Footer 고정을 위한 처리
  index.html
  src/App.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/Header/Header.tsx
  src/common/components/Main/Main.tsx
  src/common/components/index.ts
  src/pages/Home/index.tsx
Labels: Bug, Implement, React, Style

#86 로그인, 회원가입 페이지 구현(WaveFooter 컴포넌트를 곁들인...)
  src/App.css
  src/App.tsx
  src/assets/wave.svg
  src/common/components/LogoLink/LogoLink.tsx
  src/common/components/WaveFooter/WaveFooter.stories.tsx
  src/common/components/WaveFooter/WaveFooter.tsx
  src/common/components/index.ts
  src/common/styles/globalStyle.ts
  src/index.css
  src/main.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: Enhancement, Implement, React

#88 IconButton 컴포넌트 리팩토링 및 버그 수정
  src/common/components/Dialog/Dialog.stories.tsx
  src/common/components/Header/Header.tsx
  src/common/components/IconButton/IconButton.tsx
  src/common/components/TextInput/TextInput.tsx
  src/common/components/WaveFooter/WaveFooter.tsx
  src/common/components/index.ts
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: Bug, Enhancement

#89 전체 검색 결과 페이지 템플릿 구현
  index.html
  src/App.tsx
  src/common/components/AlbumInfo/AlbumInfo.stories.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/DetailInfo/DetailInfo.tsx
  src/common/components/Dropdown/Dropdown.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/Main/Main.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SearchResultText/SearchResultText.tsx
  src/common/components/SquareLink/SquareLink.tsx
  src/common/components/TitleInfo/TitleInfo.stories.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/common/components/VinylItem/VinylItem.stories.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.stories.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/common/components/index.ts
  src/main.tsx
  src/pages/Home/index.tsx
  src/pages/SearchResult/index.tsx
Labels: Bug, Enhancement, Implement, React, Style

#91 컴포넌트 리팩토링
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/IconButton/IconButton.tsx
  src/common/components/ProfileLink/ProfileLink.tsx
  src/common/components/TextInput/TextInput.tsx
  src/pages/Item/components/ArrowLink/ArrowLink.stories.tsx
  src/pages/Item/components/ArrowLink/ArrowLink.tsx
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.tsx
  src/pages/Item/components/SelectCollectionForm/SelectCollectionForm.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
Labels: Enhancement

#96 My Collections 페이지 구현 및 필요한 컴포넌트 구현&개선
  src/App.tsx
  src/common/components/Header/Header.tsx
  src/common/components/IconButton/IconButton.stories.tsx
  src/common/components/IconButton/IconButton.tsx
  src/common/components/PageTitle/PageTitle.stories.tsx
  src/common/components/PageTitle/PageTitle.tsx
  src/common/components/index.ts
  src/common/styles/globalStyle.ts
  src/pages/MyCollections/components/Bookshelf/Bookshelf.stories.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/utils/mockInfo.ts
Labels: Bug, Enhancement, Implement, React, Style

#99 타입 에러 수정 & 전체 검색 상세 페이지 구현
  src/App.tsx
  src/common/components/AlbumInfo/AlbumInfo.stories.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/DetailInfo/DetailInfo.stories.tsx
  src/common/components/DetailInfo/DetailInfo.tsx
  src/common/components/LPCover/LPCover.stories.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/VinylItem/VinylItem.stories.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.stories.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/pages/Item/index.tsx
  src/pages/SearchResult/index.tsx
  src/types/data.ts
  src/utils/constants/dropdown.ts
  src/utils/functions/processResult.ts
  src/utils/mocks/mockInfo.ts
Labels: Bug, Enhancement, Implement, React, Style

#101 전체 검색 결과 페이지 무한 스크롤 기능 구현
  index.html
  public/assets/background_img.svg
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/DetailInfo/DetailInfo.stories.tsx
  src/common/components/LPCover/LPCover.stories.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/Main/Main.tsx
  src/common/components/SearchInput/SearchInput.stories.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SquareLink/SquareLink.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/common/styles/globalStyle.ts
  src/common/styles/normalizeStyle.ts
  src/hooks/useHandleSubmit.ts
  src/pages/Home/index.tsx
  src/pages/Item/index.tsx
  src/pages/MyCollections/index.tsx
  src/pages/SearchResult/index.tsx
  src/types/data.ts
  src/utils/functions/processResult.ts
  src/utils/mocks/mockInfo.ts
Labels: Bug, Enhancement, Implement, React, Style, Config

#104 MyCollection페이지 구현
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SearchResultText/SearchResultText.tsx
  src/pages/MyCollection/index.tsx
  src/utils/mocks/mockInfo.ts
  src/utils/sortItems.ts
Labels: Enhancement, Implement, React

#103 Recoil과 Portal을 이용한 모달 구현
  .storybook/preview.jsx
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/Dialog/Dialog.stories.tsx
  src/common/components/Dialog/Dialog.tsx
  src/common/components/index.ts
  src/main.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/recoil/globalState.tsx
Labels: Bug, Implement, React, Style

#109 1차 배포를 위해 급한 에러 수정
  src/App.tsx
  src/common/components/SearchInput/SearchInput.stories.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/pages/Home/index.tsx
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.stories.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/index.tsx
  src/types/data.ts
Labels: Bug

#113 footer, header, 랜더링 관련 bug fix 및 개선과정에서 필요한 컴포넌트 구현
  src/common/components/Footer/Footer.tsx
  src/common/components/Header/Header.tsx
  src/common/components/MoveLink/MoveLink.stories.tsx
  src/common/components/MoveLink/MoveLink.tsx
  src/common/components/ScrollToTop/ScrollToTop.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SquareButton/SquareButton.tsx
  src/common/components/index.ts
  src/common/styles/globalStyle.ts
  src/hooks/useHandleSubmit.ts
  src/main.tsx
  src/pages/MyCollection/index.tsx
  src/pages/SearchResult/index.tsx
  src/utils/constants/dropdown.ts
Labels: Bug, Enhancement, Implement, React, Style

#118 My Collection 검색 상세 페이지 템플릿 구현
  public/assets/tonearm.svg
  src/App.tsx
  src/assets/close.svg
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/BackVinyl/BackVinyl.tsx
  src/common/components/DetailInfo/DetailInfo.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/ReadOnlyInfo/ReadOnlyInfo.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/common/components/WritableInfo/WritableInfo.tsx
  src/common/components/index.ts
  src/common/styles/globalStyle.ts
  src/pages/MyItem/index.tsx
  src/pages/SearchResult/index.tsx
  src/types/data.ts
  src/utils/constants/purchaseInfoName.ts
  src/utils/functions/tracklistValidator.ts
  src/utils/mocks/mockInfo.ts
Labels: Enhancement, Implement, React, Style

#120 Modal 연결 & 스타일링 수정 & 기타 리팩토링
  public/assets/background_img.svg
  public/assets/background_main.svg
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/BackVinyl/BackVinyl.tsx
  src/common/components/Dialog/Dialog.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/Main/Main.tsx
  src/common/components/ReadOnlyInfo/ReadOnlyInfo.tsx
  src/common/components/TextInput/TextInput.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/common/components/WaveFooter/WaveFooter.tsx
  src/common/components/WritableInfo/WritableInfo.tsx
  src/common/styles/globalStyle.ts
  src/pages/Home/index.tsx
  src/pages/Item/components/SelectCollectionForm/ToggleInputButton.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/pages/MyItem/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
  src/recoil/globalState.tsx
  src/utils/constants/addCollectionButtonUrl.ts
Labels: Bug, Enhancement, Implement, React, Style

#124 DB연동하여 컬렉션, 아이템 렌더링 구현
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/index.tsx
Labels: Implement, React

#121 검색 결과 페이지 및 일부 컴포넌트 렌더링 최적화
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/LogoLink/LogoLink.tsx
  src/common/components/SearchResultText/SearchResultText.tsx
  src/common/components/SquareLink/SquareLink.tsx
  src/common/components/TextInput/TextInput.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/pages/SearchResult/index.tsx
Labels: Bug, Enhancement, React, Style

#126 NotFound 페이지 구현 & Framer Motion 설치
  package-lock.json
  package.json
  public/assets/broken_vinyl_1.svg
  public/assets/broken_vinyl_2.svg
  public/assets/broken_vinyl_3.svg
  public/assets/broken_vinyl_4.svg
  public/assets/broken_vinyl_5.svg
  src/App.tsx
  src/common/components/WaveFooter/WaveFooter.tsx
  src/pages/NotFound/components/BrokenVinyls/BrokenVinyls.tsx
  src/pages/NotFound/components/index.ts
  src/pages/NotFound/index.tsx
Labels: Implement, React, Style, Config

#128 GoToTop 버튼 컴포넌트 구현 및 적용
  src/assets/gototop.svg
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/GoToTop/GoToTop.stories.tsx
  src/common/components/GoToTop/GoToTop.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/index.ts
  src/common/styles/globalStyle.ts
  src/pages/SearchResult/index.tsx
Labels: Bug, Implement, React, Style

#130 반응형 구현 & 컴포넌트 크기 조정 & 로딩 스피너 추가
  public/assets/vinyl-spinner.gif
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/Header/Header.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/pages/Home/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/pages/SearchResult/index.tsx
  src/utils/constants/addCollectionButtonUrl.ts
Labels: Bug, Enhancement, Implement, React, Style

#137 문의메일 FloatingButton 컴포넌트 및 Alert 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/csbutton.svg
  src/common/components/Alert/Alert.stories.tsx
  src/common/components/Alert/Alert.tsx
  src/common/components/FloatingButton/FloatingButton.stories.tsx
  src/common/components/FloatingButton/FloatingButton.tsx
  src/common/components/GoToTop/GoToTop.tsx
  src/common/components/SquareLink/SquareLink.tsx
  src/common/components/index.ts
  src/common/styles/normalizeStyle.ts
  src/pages/SearchResult/index.tsx
Labels: Implement, React, Style, Config

#140 GA4, GTM 연동 및 타입에러 해결
  index.html
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: Bug, Implement

#142 favicon 추가 & My Collections 페이지 제목 변경 & 기타 수정 사항 반영
  index.html
  public/assets/favicon_16.svg
  public/assets/favicon_32.svg
  public/assets/favicon_96.svg
  public/assets/logout.svg
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/PageTitle/PageTitle.tsx
  src/common/components/ProfileLink/ProfileLink.tsx
  src/pages/MyCollections/index.tsx
Labels: Enhancement, Implement, React

#144 로그인 유저의 Redirection & Floating 애니메이션 구현
  package.json
  src/pages/Home/index.tsx
  src/pages/MyCollections/index.tsx
  src/pages/NotFound/components/BrokenVinyls/BrokenVinyls.tsx
  src/pages/Signin/index.tsx
  src/utils/constants/motion.ts
  vite.config.ts
Labels: Enhancement, Implement, React, Style, Config

#148 Master, Release API 데이터 가공 함수 구현 및 적용
  public/assets/logout.svg
  src/App.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/Header/Header.tsx
  src/common/components/LoadingSpinner/LoadingSpinner.tsx
  src/common/components/ProfileLink/ProfileLink.tsx
  src/pages/Item/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.stories.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/pages/MyItem/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
  src/pages/Verification/index.tsx
  src/types/data.ts
  src/utils/functions/processResult.ts
Labels: Bug, Enhancement, Implement, React

#146 로딩 시 LP 이미지 보이는 현상 해결 & 전반적인 스타일링 수정
  src/common/components/FloatingButton/FloatingButton.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/LoadingSpinner/LoadingSpinner.tsx
  src/common/components/Main/Main.tsx
Labels: Enhancement, React, Style

#151 로그인 user와 실제 user 일치여부에 따라 조건부 랜더링 & 옵저버 option 값 설정
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/GoToTop/GoToTop.tsx
  src/common/components/IconButton/IconButton.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/pages/Item/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/pages/MyItem/index.tsx
  src/pages/SearchResult/index.tsx
Labels: Enhancement, Implement, React, Style

#153 아주 사소한 컨플릭트 해결
  src/pages/Item/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
Labels: Bug

#154 조건부 랜더링 오류 수정
  src/common/components/IconButton/IconButton.tsx
Labels: Bug

#157 최종 배포 직전, 콰트로 프로그래밍 작업
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/Alert/Alert.tsx
  src/common/components/Dialog/Dialog.stories.tsx
  src/common/components/Dialog/Dialog.tsx
  src/common/components/FloatingButton/FloatingButton.tsx
  src/common/components/Header/Header.tsx
  src/common/components/NewDialog/NewDialog.tsx
  src/common/components/ProfileLink/ProfileLink.tsx
  src/common/components/SelectCollectionForm/SelectCollectionForm.tsx
  src/common/components/SelectCollectionForm/ToggleInputButton.tsx
  src/common/components/SquareButton/SquareButton.tsx
  src/common/components/TextInput/TextInput.tsx
  src/common/components/VinylItem/VinylItem.tsx
  src/common/components/VinylItems/VinylItems.tsx
  src/common/components/index.ts
  src/pages/Item/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/pages/MyItem/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
  src/recoil/globalState.tsx
  src/utils/sortItems.ts
Labels: Bug, Enhancement, Implement, React, Style, Backend

#158 타입 오류 수정
  src/common/components/NewDialog/NewDialog.stories.tsx
  src/common/components/NewDialog/NewDialog.tsx
  src/common/components/SelectCollectionForm/SelectCollectionForm.stories.tsx
  src/common/components/TextInput/TextInput.tsx
  src/pages/Item/index.tsx
  src/pages/SearchResult/index.tsx
Labels: Bug

#161 서버 요청 경로 변경
  package-lock.json
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/pages/Item/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/index.tsx
  src/pages/SearchResult/index.tsx
Labels: Bug

#160 반응형 수정 & 기타 스타일링 변경
  src/common/components/Alert/Alert.tsx
  src/common/components/Footer/Footer.tsx
  src/common/components/Header/Header.tsx
  src/common/components/NewDialog/NewDialog.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/pages/Home/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: Bug, Enhancement, Style

#166 전반적인 애니메이션 구현 & 스타일링 수정
  public/assets/dead.svg
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/AlbumInfo/AlbumInfo.tsx
  src/common/components/Dropdown/Option.tsx
  src/common/components/FloatingButton/FloatingButton.tsx
  src/common/components/GoToTop/GoToTop.tsx
  src/common/components/IconButton/IconButton.tsx
  src/common/components/LPCover/LPCover.tsx
  src/common/components/NewDialog/NewDialog.tsx
  src/common/components/PageTitle/PageTitle.tsx
  src/common/components/ProfileLink/ProfileLink.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SearchResultText/SearchResultText.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/common/styles/globalStyle.ts
  src/pages/Item/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/MyCollections/index.tsx
  src/pages/SearchResult/index.tsx
Labels: Bug, Enhancement, Implement, React, Style

#167 자잘한 오류 수정
  src/common/components/Alert/Alert.tsx
  src/common/components/FloatingButton/FloatingButton.tsx
  src/common/components/GoToTop/GoToTop.tsx
  src/pages/MyCollection/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: Bug, Implement, React, Style

#168 드롭다운 히스토리 이동이나 새로고침 시 유지되도록 수정 및 회원가입 로딩 상태 셋팅
  src/common/components/Dropdown/Dropdown.tsx
  src/common/components/SignInAndUpForm/SignInAndUpForm.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: Bug, React, Style

#170 로그인, 회원가입 페이지 애니메이션 구현 & 스타일링 수정
  src/common/components/Footer/Footer.tsx
  src/common/components/Header/Header.tsx
  src/common/components/IconButton/IconButton.tsx
  src/common/components/SearchInput/SearchInput.tsx
  src/common/components/SignInAndUpForm/SignInAndUpForm.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/index.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: Enhancement, React, Style

#172 모달 컴포넌트 개선
  src/common/components/NewDialog/NewDialog.tsx
  src/common/components/SelectCollectionForm/SelectCollectionForm.tsx
  src/common/components/SelectCollectionForm/ToggleInputButton.tsx
Labels: Enhancement, Implement, React

#174 버그 수정 및 open graph 추가
  index.html
  src/App.tsx
  src/common/components/Header/Header.tsx
  src/common/components/SignInAndUpForm/SignInAndUpForm.tsx
  src/common/components/SignInAndUpInput/SignInAndUpInput.tsx
  src/pages/Signin/index.tsx
  src/recoil/globalState.tsx
Labels: Bug, Implement

#176 타입 오류 해결 및 툴팁 추가
  src/App.tsx
  src/common/components/Header/Header.tsx
  src/common/components/TitleInfo/TitleInfo.tsx
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/recoil/globalState.tsx
Labels: Bug, Implement

#178 필요없는 콘솔 및 주석 삭제
  src/common/components/AddCollectionButton/AddCollectionButton.tsx
  src/common/components/FloatingButton/FloatingButton.tsx
  src/common/components/GoToTop/GoToTop.tsx
  src/common/components/Header/Header.tsx
  src/common/components/ImageLink/ImageLink.tsx
  src/common/components/SelectCollectionForm/SelectCollectionForm.tsx
  src/pages/Item/components/CollectionCheckbox/CollectionCheckbox.tsx
  src/pages/Item/index.tsx
  src/pages/MyCollection/index.tsx
  src/pages/MyCollections/components/Bookshelf/Bookshelf.tsx
  src/pages/SearchResult/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
  src/recoil/globalState.tsx
  src/utils/sortItems.ts
Labels: Style

#179 회원가입 Form 로딩 버튼 구현
  src/common/components/SignInAndUpForm/SignInAndUpForm.tsx
Labels: Implement, React, Style
